"""SQLAlchemy Core table definitions for the Enterprise Gateway state database."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
)

metadata = MetaData()

ext_asset_registry = Table(
    "ext_asset_registry",
    metadata,
    Column("tenant_id", Text, primary_key=True),
    Column("equipment_id", Text, primary_key=True),
    Column("fixed_asset_no", Text),
    Column("asset_id", Text),
)

ext_document_map = Table(
    "ext_document_map",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("event_id", Text, nullable=False),
    Column("event_type", Text, nullable=False, server_default="upsert"),
    Column("event_status", Text, nullable=False, server_default="received"),
    Column("processing_round", Integer, nullable=False, server_default="1"),
    Column("sha256", Text, nullable=False),
    Column("file_name", Text, nullable=False),
    Column("media_type", Text, server_default="application/pdf"),
    Column("document_type", Text),
    Column("source_page_count", Integer),
    Column("source_kind", Text, nullable=False, server_default="S3"),
    Column("bucket", Text, nullable=False, server_default=""),
    Column("object_key", Text, nullable=False, server_default=""),
    Column("storage_root_id", Text),
    Column("relative_path", Text),
    Column("source_size", BigInteger),
    Column("source_modified_ns", BigInteger),
    Column("source_etag", Text),
    Column("asset_id", Text),
    Column("equipment_id", Text),
    Column("fixed_asset_no", Text),
    Column("department_id", Text),
    Column("security_level", Integer),
    Column("allow_group_ids", Text),
    Column("deny_group_ids", Text),
    Column("ragflow_dataset_id", Text),
    Column("ragflow_document_id", Text),
    Column("ragflow_task_id", Text),
    Column("sync_status", Text, nullable=False, server_default="received"),
    Column("pipeline_status", Text),
    Column("business_status", Text, nullable=False, server_default="active"),
    Column("current_version", Integer, nullable=False, server_default="0"),
    Column("parser_profile", Text),
    Column("parser_profile_version", Text),
    Column("parser_expected_json", Text),
    Column("parser_configured_json", Text),
    Column("parser_executed_json", Text),
    Column("parser_application_status", Text, nullable=False, server_default="legacy_unverified"),
    Column("document_subtype", Text),
    Column("source_document_type", Text),
    Column("ingest_state", Text, nullable=False, server_default="RECEIVED"),
    Column("source_state", Text, nullable=False, server_default="AVAILABLE"),
    Column("source_state_reason", Text),
    Column("attempt_count", Integer, nullable=False, server_default="0"),
    Column("parse_retry_count", Integer, nullable=False, server_default="0"),
    Column("next_retry_at", Text),
    Column("batch_id", Text),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("last_error_retryable", Integer, nullable=False, server_default="0"),
    Column("last_sync_at", Text),
    # RAGFlow 解析真正完成（sync_status 转入 ready）的时刻；存量数据不回填。
    Column("parsed_at", Text),
    Column("source_updated_at", Text),
    Column("created_at", Text, nullable=False, server_default=""),
    Column("updated_at", Text, nullable=False, server_default=""),
    UniqueConstraint(
        "tenant_id", "source_system", "external_document_id", "source_version_id",
    ),
)

Index("idx_ext_doc_event", ext_document_map.c.event_id, unique=True)
Index("idx_ext_doc_status", ext_document_map.c.tenant_id, ext_document_map.c.sync_status)
Index(
    "idx_ext_doc_doc",
    ext_document_map.c.tenant_id,
    ext_document_map.c.source_system,
    ext_document_map.c.external_document_id,
)
Index(
    "idx_ext_doc_sha",
    ext_document_map.c.tenant_id,
    ext_document_map.c.ragflow_dataset_id,
    ext_document_map.c.sha256,
)
Index("idx_ext_doc_batch", ext_document_map.c.tenant_id, ext_document_map.c.batch_id)

sync_outbox = Table(
    "sync_outbox",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("event_id", Text, nullable=False, unique=True),
    Column("event_type", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("processing_round", Integer, nullable=False, server_default="1"),
    Column("batch_id", Text),
    Column("payload", Text, nullable=False),
    Column("status", Text, nullable=False, server_default="pending"),
    Column("attempts", Integer, nullable=False, server_default="0"),
    Column("max_attempts", Integer, nullable=False, server_default="5"),
    Column("next_retry_at", Text),
    Column("locked_at", Text),
    Column("worker_id", Text),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

Index("idx_outbox_pending", sync_outbox.c.status, sync_outbox.c.next_retry_at)

ext_document_event_receipt = Table(
    "ext_document_event_receipt",
    metadata,
    Column("event_id", Text, primary_key=True),
    Column("payload_hash", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("outcome_code", Text, nullable=False),
    Column("created_at", Text, nullable=False),
)

Index(
    "idx_document_event_receipt_document",
    ext_document_event_receipt.c.tenant_id,
    ext_document_event_receipt.c.source_system,
    ext_document_event_receipt.c.external_document_id,
    ext_document_event_receipt.c.source_version_id,
)

ext_user_map = Table(
    "ext_user_map",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text),
    Column("business_subject", Text, nullable=False),
    Column("ragflow_user_id", Text),
    Column("status", Text, nullable=False, server_default="active"),
    Column("mapping_strategy", Text, nullable=False, server_default="B"),
    Column("created_at", Text, nullable=False, server_default=""),
    Column("updated_at", Text, nullable=False, server_default=""),
    Column("last_login_at", Text),
    UniqueConstraint("tenant_id", "business_subject"),
)

callback_delivery = Table(
    "callback_delivery",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("delivery_id", Text, nullable=False, unique=True),
    Column("originating_event_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("processing_round", Integer, nullable=False, server_default="1"),
    Column("terminal_status", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
    Column("payload_hash", Text, nullable=False),
    Column("endpoint_url", Text, nullable=False),
    Column("attempts", Integer, nullable=False, server_default="0"),
    Column("max_attempts", Integer, nullable=False, server_default="8"),
    Column("next_attempt_at", Text),
    Column("state", Text, nullable=False, server_default="pending"),
    Column("locked_at", Text),
    Column("worker_id", Text),
    Column("last_http_status", Integer),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    UniqueConstraint(
        "tenant_id", "source_system", "external_document_id",
        "source_version_id", "processing_round", "terminal_status",
        name="uq_callback_delivery_round_terminal",
    ),
)

Index("idx_callback_delivery_pending", callback_delivery.c.state, callback_delivery.c.next_attempt_at)

ext_citation_file_ticket = Table(
    "ext_citation_file_ticket",
    metadata,
    Column("ticket_hash", Text, primary_key=True),
    Column("citation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("kind", Text, nullable=False),
    Column("image_id", Text),
    Column("principal_json", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Column("max_downloads", Integer, nullable=False),
    Column("download_count", Integer, nullable=False, server_default="0"),
    Column("created_at", Text, nullable=False),
)

Index(
    "idx_ext_citation_file_ticket_expiry",
    ext_citation_file_ticket.c.expires_at,
    ext_citation_file_ticket.c.citation_id,
)

parse_quality_evaluation = Table(
    "parse_quality_evaluation",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("ragflow_dataset_id", Text),
    Column("ragflow_document_id", Text),
    Column("evaluation_version", Text, nullable=False, server_default="1"),
    Column("evaluation_contract_version", Text, nullable=False, server_default="1"),
    Column("thresholds_version", Text),
    Column("thresholds_digest", Text),
    Column("parser_profile", Text),
    Column("parser_version", Text),
    Column("routing_policy_version", Text),
    Column("routing_reasons", Text, nullable=False, server_default="[]"),
    Column("evaluation_state", Text, nullable=False, server_default="pending"),
    Column("parse_quality_status", Text),
    Column("quality_reasons", Text, nullable=False, server_default="[]"),
    Column("metrics_json", Text, nullable=False, server_default="{}"),
    Column("parse_repeatability_hash", Text),
    Column("e2e_repeatability_hash", Text),
    Column("artifact_hash", Text),
    Column("enterprise_commit", Text),
    Column("enterprise_worktree_dirty", Integer, nullable=False, server_default="0"),
    Column("ragflow_source_tag", Text),
    Column("ragflow_source_commit", Text),
    Column("attempt_count", Integer, nullable=False, server_default="0"),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("started_at", Text),
    Column("completed_at", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    UniqueConstraint(
        "tenant_id", "source_system", "external_document_id",
        "source_version_id", "evaluation_version",
    ),
)

quality_evaluation_job = Table(
    "quality_evaluation_job",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("evaluation_id", Integer, nullable=False, unique=True),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("evaluation_version", Text, nullable=False, server_default="1"),
    Column("status", Text, nullable=False, server_default="pending"),
    Column("attempts", Integer, nullable=False, server_default="0"),
    Column("max_attempts", Integer, nullable=False, server_default="5"),
    Column("next_retry_at", Text),
    Column("locked_at", Text),
    Column("worker_id", Text),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

ext_v2_conversation = Table(
    "ext_v2_conversation",
    metadata,
    Column("conversation_id", Text, primary_key=True),
    Column("tenant_id", Text, primary_key=True),
    Column("business_user_id", Text, primary_key=True),
    Column("title", Text, nullable=False, server_default="New conversation"),
    Column("equipment_id", Text),
    Column("fixed_asset_no", Text),
    Column("asset_id", Text),
    Column("fault_code", Text),
    Column("context_version", Integer, nullable=False, server_default="0"),
    Column("status", Text, nullable=False, server_default="active"),
    Column("ragflow_chat_id", Text),
    Column("ragflow_session_id", Text),
    Column("context_summary", Text),
    Column("summary_updated_at", Text),
    Column("compressed_turn_watermark", Integer, nullable=False, server_default="0"),
    Column("registry_version", Text),
    Column("context_resolved_at", Text),
    Column("first_message_at", Text),
    Column("created_at", Text, nullable=False),
    Column("last_message_at", Text, nullable=False),
)

ext_v2_message = Table(
    "ext_v2_message",
    metadata,
    Column("message_id", Text, primary_key=True),
    Column("conversation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("content", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("citations_json", Text, nullable=False, server_default="[]"),
    Column("attachments_json", Text, nullable=False, server_default="[]"),
    Column("reasoning", Text),
    Column("created_at", Text, nullable=False),
)

ext_v2_message_run = Table(
    "ext_v2_message_run",
    metadata,
    Column("conversation_id", Text, primary_key=True),
    Column("tenant_id", Text, primary_key=True),
    Column("business_user_id", Text, primary_key=True),
    Column("client_message_id", Text, primary_key=True),
    Column("request_hash", Text, nullable=False),
    Column("run_id", Text, nullable=False),
    Column("status", Text, nullable=False, server_default="running"),
    Column("lease_expires_at", Text),
    Column("user_message_id", Text),
    Column("assistant_message_id", Text),
    Column("result_json", Text),
    Column("entity_scope_json", Text),
    Column("allowed_doc_ids_json", Text),
    Column("created_at", Text, nullable=False),
)

ext_v2_citation = Table(
    "ext_v2_citation",
    metadata,
    Column("citation_id", Text, primary_key=True),
    Column("message_id", Text, nullable=False),
    Column("conversation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("snapshot_json", Text, nullable=False),
    Column("created_at", Text, nullable=False),
)

demo_document_acl = Table(
    "demo_document_acl",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    UniqueConstraint("tenant_id", "external_document_id", "business_user_id"),
)

ext_conversation_map = Table(
    "ext_conversation_map",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("business_conversation_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("ragflow_chat_id", Text),
    Column("ragflow_session_id", Text),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text),
    Column("asset_id", Text),
    Column("equipment_id", Text),
    Column("fixed_asset_no", Text),
    Column("current_fault_code", Text),
    Column("status", Text, nullable=False, server_default="active"),
    Column("created_at", Text, nullable=False),
    Column("last_message_at", Text),
    UniqueConstraint("tenant_id", "business_user_id", "business_conversation_id"),
)

ext_conversation_message = Table(
    "ext_conversation_message",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("conversation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("message_id", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("status", Text, nullable=False, server_default="completed"),
    Column("ragflow_message_id", Text),
    Column("content", Text),
    Column("citations_json", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

ext_conversation = Table(
    "ext_conversation",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("conversation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("equipment_id", Text),
    Column("fixed_asset_no", Text),
    Column("current_fault_code", Text),
    Column("status", Text, nullable=False, server_default="active"),
    Column("ragflow_chat_id", Text),
    Column("ragflow_session_id", Text),
    Column("created_at", Text, nullable=False),
    Column("last_message_at", Text),
    UniqueConstraint("tenant_id", "business_user_id", "conversation_id"),
)

ext_conversation_citation = Table(
    "ext_conversation_citation",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("citation_id", Text, nullable=False, unique=True),
    Column("message_id", Text, nullable=False),
    Column("conversation_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("source_type", Text, nullable=False, server_default="document"),
    Column("title", Text, nullable=False),
    Column("document_id", Text),
    Column("ragflow_document_id", Text),
    Column("chunk_id", Text),
    Column("source_version_id", Text),
    Column("asset_id", Text),
    Column("page_no", Integer),
    Column("bbox_json", Text),
    Column("image_id", Text),
    Column("positions_json", Text),
    Column("evidence_json", Text),
    Column("excerpt", Text),
    Column("record_type", Text),
    Column("record_id", Text),
    Column("created_at", Text, nullable=False),
)

ext_transient_attachment = Table(
    "ext_transient_attachment",
    metadata,
    Column("attachment_id", Text, primary_key=True),
    Column("tenant_id", Text, nullable=False),
    Column("conversation_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("object_bucket", Text, nullable=False),
    Column("object_key", Text, nullable=False),
    Column("file_name", Text, nullable=False),
    Column("media_type", Text, nullable=False),
    Column("extension", Text, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("sha256", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Column("max_downloads", Integer, nullable=False, server_default="1"),
    Column("download_count", Integer, nullable=False, server_default="0"),
    Column("status", Text, nullable=False, server_default="uploading"),
    Column("upload_attempts", Integer, nullable=False, server_default="0"),
    Column("delete_attempts", Integer, nullable=False, server_default="0"),
    Column("next_retry_at", Text),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("deleted_at", Text),
    Column("ragflow_file_id", Text),
    Column("ragflow_file_deleted_at", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

ext_transient_attachment_ticket = Table(
    "ext_transient_attachment_ticket",
    metadata,
    Column("ticket_hash", Text, primary_key=True),
    Column("attachment_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("conversation_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Column("claimed_at", Text),
    Column("claim_expires_at", Text),
    Column("consumed_at", Text),
    Column("download_attempts", Integer, nullable=False, server_default="0"),
    Column("last_error_code", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

ext_transient_attachment_audit = Table(
    "ext_transient_attachment_audit",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("attachment_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("conversation_id", Text, nullable=False),
    Column("business_user_id", Text, nullable=False),
    Column("action", Text, nullable=False),
    Column("outcome", Text, nullable=False),
    Column("request_id", Text),
    Column("metadata_json", Text, nullable=False, server_default="{}"),
    Column("created_at", Text, nullable=False),
)

ext_ragflow_temp_file = Table(
    "ext_ragflow_temp_file",
    metadata,
    Column("file_id", Text, primary_key=True),
    Column("created_at", Text, nullable=False),
    Column("deleted_at", Text),
)

parsing_import_batch = Table(
    "parsing_import_batch",
    metadata,
    Column("batch_id", Text, primary_key=True),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("idempotency_key", Text, nullable=False),
    Column("manifest_hash", Text, nullable=False),
    Column("status", Text, nullable=False, server_default="pending"),
    Column("total_items", Integer, nullable=False),
    Column("checkpoint_sequence", Integer, nullable=False, server_default="-1"),
    Column("checkpoint_item_id", Integer),
    Column("attempt_count", Integer, nullable=False, server_default="0"),
    Column("completed_items", Integer, nullable=False, server_default="0"),
    Column("deduplicated_items", Integer, nullable=False, server_default="0"),
    Column("conflict_items", Integer, nullable=False, server_default="0"),
    Column("failed_items", Integer, nullable=False, server_default="0"),
    Column("review_required_items", Integer, nullable=False, server_default="0"),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    UniqueConstraint("tenant_id", "source_system", "idempotency_key"),
)

parsing_import_item = Table(
    "parsing_import_item",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("batch_id", Text, nullable=False),
    Column("sequence", Integer, nullable=False),
    Column("item_key", Text, nullable=False),
    Column("event_id", Text, nullable=False),
    Column("effective_event_id", Text, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("sha256", Text, nullable=False),
    Column("payload_hash", Text, nullable=False),
    Column("payload_json", Text, nullable=False),
    Column("item_status", Text, nullable=False, server_default="pending"),
    Column("outcome_code", Text),
    Column("retryable", Integer, nullable=False, server_default="0"),
    Column("attempt_count", Integer, nullable=False, server_default="0"),
    Column("next_retry_at", Text),
    Column("claimed_at", Text),
    Column("worker_id", Text),
    Column("last_error_code", Text),
    Column("last_error_message", Text),
    Column("document_sync_status", Text),
    Column("document_business_status", Text),
    Column("document_current_version", Integer),
    Column("parser_application_status", Text),
    Column("quality_status", Text),
    Column("persisted_state_json", Text, nullable=False, server_default="{}"),
    Column("duplicate_of_item_id", Integer),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    UniqueConstraint("batch_id", "sequence"),
)

parsing_review = Table(
    "parsing_review",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("batch_id", Text, nullable=False),
    Column("item_id", Integer, nullable=False),
    Column("tenant_id", Text, nullable=False),
    Column("source_system", Text, nullable=False),
    Column("external_document_id", Text, nullable=False),
    Column("source_version_id", Text, nullable=False),
    Column("review_status", Text, nullable=False, server_default="review_required"),
    Column("decision", Text),
    Column("operator_id", Text),
    Column("reviewed_at", Text),
    Column("reason", Text, nullable=False),
    Column("before_state_json", Text, nullable=False, server_default="{}"),
    Column("after_state_json", Text, nullable=False, server_default="{}"),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
)

parsing_audit_event = Table(
    "parsing_audit_event",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("tenant_id", Text, nullable=False),
    Column("batch_id", Text),
    Column("item_id", Integer),
    Column("review_id", Integer),
    Column("actor_id", Text, nullable=False),
    Column("action", Text, nullable=False),
    Column("reason", Text),
    Column("before_state_json", Text, nullable=False, server_default="{}"),
    Column("after_state_json", Text, nullable=False, server_default="{}"),
    Column("request_id", Text),
    Column("occurred_at", Text, nullable=False),
)

# Indexes that were previously created by per-module SQLite bootstrap scripts.
Index("idx_ext_conversation_user", ext_conversation_map.c.tenant_id, ext_conversation_map.c.business_user_id)
Index("idx_ext_conversation_message_conv", ext_conversation_message.c.conversation_id)
Index("idx_ext_conversation_owner", ext_conversation.c.tenant_id, ext_conversation.c.business_user_id)
Index("idx_ext_conversation_citation_message", ext_conversation_citation.c.message_id)
Index("idx_ext_conversation_citation_conv", ext_conversation_citation.c.conversation_id)
Index("idx_ext_conversation_citation_doc", ext_conversation_citation.c.document_id)
Index("idx_quality_eval_doc", parse_quality_evaluation.c.tenant_id, parse_quality_evaluation.c.source_system, parse_quality_evaluation.c.external_document_id, parse_quality_evaluation.c.source_version_id)
Index("idx_quality_eval_state", parse_quality_evaluation.c.evaluation_state, parse_quality_evaluation.c.parse_quality_status)
Index("idx_quality_job_pending", quality_evaluation_job.c.status, quality_evaluation_job.c.next_retry_at)
Index("idx_parsing_import_item_status", parsing_import_item.c.batch_id, parsing_import_item.c.item_status, parsing_import_item.c.sequence)
Index("idx_parsing_import_item_identity", parsing_import_item.c.tenant_id, parsing_import_item.c.source_system, parsing_import_item.c.external_document_id, parsing_import_item.c.source_version_id)
Index("idx_parsing_review_open_item", parsing_review.c.item_id, unique=True, postgresql_where=parsing_review.c.review_status == "review_required")
Index("idx_parsing_review_queue", parsing_review.c.tenant_id, parsing_review.c.review_status, parsing_review.c.created_at)
Index("idx_parsing_audit_tenant_time", parsing_audit_event.c.tenant_id, parsing_audit_event.c.occurred_at, parsing_audit_event.c.id)
Index("idx_parsing_audit_batch", parsing_audit_event.c.batch_id, parsing_audit_event.c.occurred_at, parsing_audit_event.c.id)
Index("idx_ext_transient_attachment_expiry", ext_transient_attachment.c.status, ext_transient_attachment.c.expires_at, ext_transient_attachment.c.next_retry_at)
Index("idx_ext_transient_attachment_owner", ext_transient_attachment.c.tenant_id, ext_transient_attachment.c.conversation_id, ext_transient_attachment.c.business_user_id)
Index("idx_ext_transient_ticket_expiry", ext_transient_attachment_ticket.c.expires_at, ext_transient_attachment_ticket.c.consumed_at)
Index("idx_ext_transient_audit_attachment", ext_transient_attachment_audit.c.attachment_id, ext_transient_attachment_audit.c.created_at)
Index("idx_ext_ragflow_temp_file_pending", ext_ragflow_temp_file.c.deleted_at, ext_ragflow_temp_file.c.created_at)

gateway_schema_version = Table(
    "gateway_schema_version",
    metadata,
    Column("version", Integer, primary_key=True),
    Column("applied_at", Text, nullable=False),
)

gateway_runtime_settings = Table(
    "gateway_runtime_settings",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("settings_json", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("updated_by", Text),
    CheckConstraint("id = 1", name="ck_gateway_runtime_settings_singleton"),
)

ALL_TABLES = (
    ext_asset_registry,
    ext_document_map,
    sync_outbox,
    ext_document_event_receipt,
    ext_user_map,
    callback_delivery,
    ext_citation_file_ticket,
    parse_quality_evaluation,
    quality_evaluation_job,
    ext_v2_conversation,
    ext_v2_message,
    ext_v2_message_run,
    ext_v2_citation,
    demo_document_acl,
    ext_conversation_map,
    ext_conversation_message,
    ext_conversation,
    ext_conversation_citation,
    ext_transient_attachment,
    ext_transient_attachment_ticket,
    ext_transient_attachment_audit,
    ext_ragflow_temp_file,
    parsing_import_batch,
    parsing_import_item,
    parsing_review,
    parsing_audit_event,
    gateway_runtime_settings,
)
